services:
  - type: worker
    name: shayari-poster
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: FACEBOOK_PAGE_ID
        sync: false
      - key: FACEBOOK_ACCESS_TOKEN
        sync: false
